- min

- max

- mean

- median 

- mode

- variance

- standard deviation

- covariance

- correlation

- z score

- min max scaler

In [1]:
l = list(range(1,11))
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
min(l)

1

In [3]:
max(l)

10

In [4]:
import numpy as np

In [5]:
np.mean(l)

np.float64(5.5)

In [6]:
np.min(l)

np.int64(1)

In [7]:
np.max(l)

np.int64(10)

In [8]:
np.median(l)

np.float64(5.5)

In [9]:
np.mode(l)

AttributeError: module 'numpy' has no attribute 'mode'

In [10]:
np.var(l)

np.float64(8.25)

In [11]:
np.std(l)

np.float64(2.8722813232690143)

In [12]:
l1 = [1,2,3,4,5,6]
arr1 = np.array(l1)
l2 = [7,8,9,10,11,12]
arr2 = np.array(l2)

In [13]:
l3 = [l1,l2]
np.cov(l3)

array([[3.5, 3.5],
       [3.5, 3.5]])

In [14]:
np.corrcoef(l3)

array([[1., 1.],
       [1., 1.]])

In [15]:
np.corrcoef(l)

np.float64(1.0)

In [3]:
import numpy as np
l = list(range(10,101,10))
arr1 = np.array(l)

In [4]:
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**min**

In [5]:
np.min(arr1)

np.int64(10)

**max**

In [6]:
np.max(arr1)

np.int64(100)

**sum**

In [7]:
np.sum(arr1)

np.int64(550)

**count non zero**

In [8]:
np.count_nonzero(arr1)

10

**mean**

In [11]:
# direct
np.mean(arr1)

np.float64(55.0)

In [10]:
SUM = np.sum(arr1)
count = np.count_nonzero(arr1)
SUM/count

np.float64(55.0)

**median**

In [12]:
np.median(arr1)

np.float64(55.0)

**variance**

In [13]:
np.var(arr1)

np.float64(825.0)

In [14]:
SUM = np.sum(arr1)
count = np.count_nonzero(arr1)
mean = SUM/count

In [30]:
# step 1 : arr1 (xi means array)
print(arr1)
# step 2 : mean (xbar means mean of array)
mean = np.mean(arr1)
print(mean)
# step 3 : arr1-mean (calculate xi-xbar in the form of array)
arr2 = arr1-mean
print(arr2)
# step 4 : square ( square of xi - xbar)
arr3 = np.square(arr2)
print(arr3)
# step 5 : sum ( numerator = sum of square of xi - xbar)
arr4 = np.sum(arr3)
print(arr4)
# step 6 : calculation (numerator / count)
var = arr4 / np.count_nonzero(arr1)
print(var)

[ 10  20  30  40  50  60  70  80  90 100]
55.0
[-45. -35. -25. -15.  -5.   5.  15.  25.  35.  45.]
[2025. 1225.  625.  225.   25.   25.  225.  625. 1225. 2025.]
8250.0
825.0


In [36]:
a = np.sum(np.square(arr1-np.mean(arr1))) / np.count_nonzero(arr1)
a

np.float64(825.0)

**standard deviation**

In [33]:
np.std(arr1)

np.float64(28.722813232690143)

In [32]:
# step 1 : arr1 (xi means array)
print(arr1)
# step 2 : mean (xbar means mean of array)
mean = np.mean(arr1)
print(mean)
# step 3 : arr1-mean (calculate xi-xbar in the form of array)
arr2 = arr1-mean
print(arr2)
# step 4 : square ( square of xi - xbar)
arr3 = np.square(arr2)
print(arr3)
# step 5 : sum ( numerator = sum of square of xi - xbar)
arr4 = np.sum(arr3)
print(arr4)
# step 6 : calculation (numerator / count)
var = arr4 / np.count_nonzero(arr1)
print(var)
# step 7 : square root of var for standard deviation
std = np.sqrt(var)
print(std)

[ 10  20  30  40  50  60  70  80  90 100]
55.0
[-45. -35. -25. -15.  -5.   5.  15.  25.  35.  45.]
[2025. 1225.  625.  225.   25.   25.  225.  625. 1225. 2025.]
8250.0
825.0
28.722813232690143


In [39]:
np.sqrt((np.sum(np.square(arr1-np.mean(arr1))))/np.count_nonzero(arr1))

np.float64(28.722813232690143)

**covariance**

In [41]:
x = range(1,11)
y = range(100,110)
len(x),len(y)

(10, 10)

In [42]:
list(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
list(y)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]

In [45]:
arr_1 = np.array(x)
arr_2 = np.array(y)
print(arr_1)
print(arr_2)

[ 1  2  3  4  5  6  7  8  9 10]
[100 101 102 103 104 105 106 107 108 109]


In [46]:
np.cov(arr_1,arr_2)

array([[9.16666667, 9.16666667],
       [9.16666667, 9.16666667]])

In [49]:
np.mean(arr_1)

np.float64(5.5)

In [50]:
np.mean(arr_2)

np.float64(104.5)

In [52]:
xi = np.array(arr_1-np.mean(arr_1))
xi

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [53]:
yi = np.array(arr_2-np.mean(arr_2))
yi

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [55]:
xi*yi

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [57]:
np.sum(xi*yi)

np.float64(82.5)

In [59]:
np.sum(xi*yi) / (np.count_nonzero(arr_1) - 1)

np.float64(9.166666666666666)

In [70]:
np.sum(np.array(arr_1-np.mean(arr_1)) * np.array(arr_2-np.mean(arr_2))) / (np.count_nonzero(arr_1) - 1)

np.float64(9.166666666666666)

In [77]:
np.sum(np.array(arr_1-np.mean(arr_1)) * np.array(arr_2-np.mean(arr_2))) / (np.sqrt(np.sum(np.square(arr_1-np.mean(arr_1))) * np.sum(np.square(arr_2-np.mean(arr_2)))))

np.float64(1.0)

In [73]:
np.sum(np.square(arr_1-np.mean(arr_1)))

np.float64(82.5)

In [74]:
np.sum(np.square(arr_2-np.mean(arr_2)))

np.float64(82.5)

In [82]:
np.sum(np.square(arr_1-np.mean(arr_1))) * np.sum(np.square(arr_2-np.mean(arr_2)))

np.float64(6806.25)

In [76]:
np.sqrt(np.sum(np.square(arr_1-np.mean(arr_1))) * np.sum(np.square(arr_2-np.mean(arr_2))))

np.float64(82.5)

In [78]:
np.corrcoef(arr_1,arr_2)

array([[1., 1.],
       [1., 1.]])

**euclidean distance**

In [83]:
x_1 = (10,20)
y_1 = (5,6)

In [85]:
arr_3 = np.array(x_1)
arr_4 = np.array(y_1)

In [86]:
print(arr_3)
print(arr_4)

[10 20]
[5 6]


In [88]:
arr_3-arr_4

array([ 5, 14])

In [89]:
np.square(arr_3-arr_4)

array([ 25, 196])

In [90]:
np.sum(np.square(arr_3-arr_4))

np.int64(221)

In [91]:
np.sqrt(np.sum(np.square(arr_3-arr_4)))

np.float64(14.866068747318506)

In [92]:
from numpy.linalg import norm

In [93]:
norm(arr_3-arr_4)

np.float64(14.866068747318506)

**cosine similarity**

In [94]:
x = [1,2,3]
y = [4,5,6]

In [95]:
ar_1 = np.array(x)
ar_2 = np.array(y)
print(ar_1)
print(ar_2)

[1 2 3]
[4 5 6]


In [97]:
# convert into array
# NR = np.dot()
# dr = a * b
# a = norm(arr1)
numerator = np.dot(ar_1,ar_2)
denominator = norm(ar_1) * norm(ar_2)

In [98]:
numerator

np.int64(32)

In [99]:
denominator

np.float64(32.83291031876401)

In [100]:
numerator/ denominator

np.float64(0.9746318461970762)