**1D**

In [1]:
import numpy as np
l1 = [1,2,3,4]
arr1 = np.array(l1)
arr1

array([1, 2, 3, 4])

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [4]:
arr1.ndim # it shows how many number of dimensions are there

1

In [5]:
arr1.shape # number of rows and number of columns

(4,)

In [6]:
arr1.size # number of elements

4

**2D**

In [7]:
l1 = [10,20,30,40]
l2 = [1,2,3,4]
np.array(l1,l2)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [8]:
# np.array(object,dtype) 
# above it is taking l1 as object and l2 as dtype hence it will throw wrror in order we have to store l1 and l2 in seperate list l3

In [9]:
l3= [l1,l2]
arr2 = np.array(l3)
arr2

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.size

8

In [12]:
arr2.ndim

2

In [13]:
l_1 = [10,20,30,40]
l_2 = [1,2,3,4]
l_3 = [5,6,7,8]
l_4 = [l_1,l_2,l_3]
arr3 = np.array(l_4)
arr3

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [14]:
arr3.shape

(3, 4)

In [15]:
arr3.size

12

In [16]:
arr3.ndim

2

In [17]:
len(arr3)

3

In [19]:
arr3[0,0]

np.int64(10)

In [20]:
l_11 = [10,20,30,40]
l_22 = [1,2,3,4]
l_33 = [5,6,7,8]
l_44 = [9,10,11,12]
l_updated = [[[l_11,l_22,l_33,l_44]]]
arr4 = np.array(l_updated)

In [21]:
arr4

array([[[[10, 20, 30, 40],
         [ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [22]:
arr4.ndim

4

In [23]:
arr4.size

16

In [24]:
arr4.shape

(1, 1, 4, 4)

In [25]:
arr4[0,0,0,0]

np.int64(10)

In [26]:
# 2,4
b = [1,2,3,4]
a = [b,b]
np.array(a)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [27]:
np.array(a).shape

(2, 4)

In [28]:
l1 = [1,2,3,4]
l2 = ['A','B','C','D']
a = [l1,l2]
np.array(a).shape

(2, 4)

In [29]:
# 3,3,4
l1 = [1,2,3,4]
l2 = ['A','B','C','D']
l3 = [5,6,7,8]
l4 = [l1,l2,l3]
l5 = [l4,l4,l4]
np.array(l5)

array([[['1', '2', '3', '4'],
        ['A', 'B', 'C', 'D'],
        ['5', '6', '7', '8']],

       [['1', '2', '3', '4'],
        ['A', 'B', 'C', 'D'],
        ['5', '6', '7', '8']],

       [['1', '2', '3', '4'],
        ['A', 'B', 'C', 'D'],
        ['5', '6', '7', '8']]], dtype='<U21')

In [30]:
np.array(l5).shape

(3, 3, 4)

In [31]:
l_11 = [10,20,30,40]
l_22 = [1,2,3,4]
l_33 = [5,6,7,8]
l_44 = [9,10,11,12]
l_updated = [l_11,l_22,l_33,l_44]
arr5 = np.array(l_updated)

In [32]:
arr5.shape

(4, 4)

In [33]:
arr5

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr5.size

16

In [35]:
arr5.ndim

2